# Generated by Django 2.2.4 on 2019-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potshop', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
