# Generated by Django 2.2.4 on 2019-09-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potshop', '0006_auto_20190925_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=700),
            preserve_default=False,
        ),
    ]
