# Generated by Django 2.2.4 on 2019-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potshop', '0008_auto_20190925_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is a test description 1234'),
            preserve_default=False,
        ),
    ]
